name: deploy gh-pages

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      SECRET : ${{ secrets.deploy_secret }}
      PUBLISH: ./build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps: 
      - uses: actions/checkout@v2
      
      - name: Install and build
        run: |
          yarn install
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          TOKEN: ${{ secrets.deploy_secret }}
          BRANCH: gh-pages
          FOLDER: .
