name: deploy gh-pages

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      SECRET : ${{ secrets.deploy_secret }}
      PUBLISH: ./build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps: 
      - name: Checkout to the repository
        uses: actions/checkout@v3
      
      - name: Setup setup-node and add yarn cache option
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'yarn'

      - name: Install (or use cache file) and Test
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Build
        run: yarn run build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          TOKEN: ${{ secrets.deploy_secret }}
          BRANCH: gh-pages
          FOLDER: build
